// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rwjeakjcaoybtnshmcur.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ3amVha2pjYW95YnRuc2htY3VyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM3Mjk4NDcsImV4cCI6MjA2OTMwNTg0N30.7tmVKW7HQGjZf4Jx8ufpn1vQ1dnTSbiUPc_8W914mqs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});